---
title: "Lockdown Opinions & Lockdown Behaviours"
subtitle: "DATA10001 Project 2"
author: "510516927, "
output:
  html_document:
    code_download: true # embed .Rmd file
    number_sections: true 
    theme: lumen # theme the doc
    highlight: tango # theme syntax colouring
    fig_caption: yes
    self_contained: yes
    code_folding: hide
---

```{r, echo = F}
library(tidyverse)
library(ggthemes)
library(wesanderson)
library(ggplot2)
```

```{r, message = F}
survey = read.csv("P2 Final.csv")

survey_fresh = survey %>%
                    rename(
                      `Age` = 1,
                      `LGA` = 2,
                      `Opinion on lockdown` = 3,
                      `Following rules` = 4,
                      `Cohabitation` = 5,
                      `Income` = 6,
                      `Lockdown time outdoors` = 7, 
                      `Lockdown time exercising` = 8,
                      `Exercise hours` = 9,
                      `Low mood` = 10,
                      `Happy mood` = 11,
                      `Hours technology` = 12
                       )

```

```{r}
# ggplot(survey_fresh, aes(x = `Exercise hours`, y = `Low mood`, color = as.factor(`Opinion on lockdown`))) + 
#   geom_point() +
#   geom_smooth(color = wes_palette(n = 1, "GrandBudapest1"), method = "lm", se=FALSE, aes(color = NULL)) +
#   scale_color_manual(values = wes_palette(n = 5, "GrandBudapest2", type = "continuous")) +
#   geom_count() +
#   labs(
#     title = "Weekly Exercise and Mood",
#     x = "Weekly Exercise (Hours)",
#     y = "Low mood (Days / week)",
#     color = "Opinion on Lockdown\n(1-5, Linkert Scale)"
#   )
```

```{r}
ggplot(survey_fresh, aes(x = `Exercise hours`, y = `Low mood`, color = "GrandBudapest1")) + 
  guides(color = FALSE) +
  geom_point() +
  geom_smooth(color = wes_palette(n = 1, "GrandBudapest1"), method = "lm", se=FALSE) +
  theme_classic() +
  geom_jitter() +
  labs(
    title = "Weekly Exercise and Mood",
    x = "Weekly Exercise (Hours)",
    y = "Low mood (Days / week)",
    color = "Opinion on Lockdown\n(1-5, Linkert Scale)"
  )

cor(survey_fresh$`Exercise hours`,survey_fresh$`Low mood`)

R1 = lm(survey_fresh$`Exercise hours` ~ survey_fresh$`Low mood`)

ggplot(survey_fresh, aes(y=R1$residuals, x=survey_fresh$`Low mood`)) +
  geom_point() +
  geom_hline(yintercept=0, colour = "aquamarine3", size = 1) +
  theme_classic() +
  labs (
    title = "Residuals",
    x = "Exercise hours",
    y = "Low mood"
  )
```

```{r}
ggplot(survey_fresh, aes(x = `Exercise hours`, y = `Happy mood`, color = "GrandBudapest1")) + 
  guides(color = FALSE) +
  geom_point() +
  geom_smooth(color = wes_palette(n = 1, "GrandBudapest1"), method = "lm", se=FALSE) +
  theme_classic() +
  geom_jitter() +
  labs(
    title = "Weekly Exercise and Mood",
    x = "Weekly Exercise (Hours)",
    y = "Happy Mood (Days / week)",
    color = "Opinion on Lockdown\n(1-5, Linkert Scale)"
  )

cor(survey_fresh$`Exercise hours`,survey_fresh$`Happy mood`)

R1 = lm(survey_fresh$`Exercise hours` ~ survey_fresh$`Happy mood`)

ggplot(survey_fresh, aes(y=R1$residuals, x=survey_fresh$`Happy mood`)) +
  geom_point() +
  geom_hline(yintercept=0, colour = "aquamarine3", size = 1) +
  theme_classic() +
  labs (
    title = "Residuals",
    x = "Exercise hours",
    y = "Happy Mood"
  )
```


```{r}
lgavsexercise <- data.frame(x = survey_fresh$`LGA`, y = survey_fresh$`Exercise hours`)

ggplot(lgavsexercise, aes(x,y, colour = survey_fresh$LGA))+
  geom_boxplot( aes(fill = survey_fresh$LGA)) +
  scale_y_log10() +
  #facet_wrap(survey_fresh$Cohabitation)
  theme_linedraw()+
  labs()

# ggplot(survey_fresh, aes(x = `Exercise hours`, y = `Low mood` )) +
#   geom_point() +
#   labs() +
#   geom_smooth(method = "lm")
```

```{r}
survey_fresh$`Following rules` = factor(survey_fresh$`Following rules`)

ggplot(survey_fresh, aes(x = as.factor(`Opinion on lockdown`))) + 
  geom_bar(aes(fill=`Following rules`)) +
  labs()

ggplot(survey_fresh, aes(x = `Opinion on lockdown`, y = as.numeric(`Following rules`))) + 
  geom_point() +
  geom_jitter() +
  geom_rangeframe() +
  labs() +
  geom_smooth(method = "lm")


cor(survey_fresh$`Opinion on lockdown`,as.numeric(survey_fresh$`Following rules`))
```

```{r}
library(dplyr)

# LGA_Ranked <- 
#   survey_fresh %>%
#   mutate(new_x = case_when(
#   x == `LGA of "concern"`  ~ 0,
#   x == `Greater Sydney`  ~ 1,
#   x == `Regional or Rural NSW`” ~ 2,
#   x == `strongly agree` ~ 3,
#   TRUE   ~ NA_real))

Ranked_LGA<-recode(survey_fresh$`LGA`, 'LGA of "concern"'=0, 'Greater Sydney'=1, 'Regional or Rural NSW'=2, 'International'=3)
Ranked_LGA


ggplot(survey_fresh, aes(x = `Lockdown time exercising`, y = as.numeric(`Low mood`))) + 
  geom_point() +
  facet_wrap(~`LGA`) + 
  geom_jitter() +
  geom_rangeframe() +
  labs() +
  geom_smooth(method = "lm")


cor(survey_fresh$`Opinion on lockdown`,as.numeric(survey_fresh$`Following rules`))
```

# Premises
## Strongly correlated - As weekly exercise declines, days of low mood increases - Vice versa for happy mood
## Those in LGAs of concern will show the greatest exercise decline of all locales
# Hence, those in LGAs of concern are the least happy during lockdown


# As opinion on lockdown increases, as does rule-following

